import type { Metadata } from "next";
import "./globals.css";
import AppSettingsProvider from "@/components/AppSettingsProvider";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <AppSettingsProvider>
          <NavBar />
          {children}
        </AppSettingsProvider>
      </body>
    </html>
  );
}
